version: '3.6'
services:
  nats:
    image: nats-streaming:0.16.2
    restart: on-failure
    ports:
      - 4222:4222
  postgres:
    image: postgres:12-alpine
    restart: always
    networks:
      - default
    ports:
      - 5435:5432
    volumes:
      - .volumes:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 5
  vulnerability-scanner:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - GITHUB_ACCESS_TOKEN=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
      - NATS_URL=nats://nats:4222
volumes:
  db_data:

networks:
  default: